                                                                                                                                              <input
                                                                                                                                                      className="search-input"
                                                                                                                                                              type="text"
                                                                                                                                                                      value={searchQuery}
                                                                                                                                                                              onChange={(e) => setSearchQuery(e.target.value)}
                                                                                                                                                                                      placeholder="Search for a movie..."
                                                                                                                                                                                            />
                                                                                                                                                                                                  <ul className="movie-list">
                                                                                                                                                                                                          {filteredMovies.length > 0 ? (
                                                                                                                                                                                                                    filteredMovies.map((movie, index) => (
                                                                                                                                                                                                                                <li className="movie-item" key={index}>{movie}</li>
                                                                                                                                                                                                                                          ))
                                                                                                                                                                                                                                                  ) : (
                                                                                                                                                                                                                                                            <div className="no-results">
                                                                                                                                                                                                                                                                        {searchQuery ? 'No movies found. Try a different search.' : 'Start typing to search movies...'}
                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                </ul>
                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                                      export default MovieSearch;