                                                                                                                                                                                                    <div>
                                                                                                                                                                                                                <h2>Work Experience & Skills</h2>
                                                                                                                                                                                                                            <p>Content for Work Experience & Skills will go here.</p>
                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                              )}

                                                                                                                                                                                                                                                      {currentActiveTab === 2 && (
                                                                                                                                                                                                                                                                <div>
                                                                                                                                                                                                                                                                            <h2>Review Your Application</h2>
                                                                                                                                                                                                                                                                                        <p>Content for Review Your Application will go here.</p>
                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                          )}
                                                                                                                                                                                                                                                                                                                </div>

                                                                                                                                                                                                                                                                                                                      <div className="tab-navigation">
                                                                                                                                                                                                                                                                                                                              <button>Previous</button>
                                                                                                                                                                                                                                                                                                                                      <button>Next</button>
                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                  export default Tabs;