                                                                                                                                                                                                                <p className="empty-message">No todos</p>
                                                                                                                                                                                                                      ) : (
                                                                                                                                                                                                                              <ul>
                                                                                                                                                                                                                                        {todos.map((todo) => (
                                                                                                                                                                                                                                                    <li
                                                                                                                                                                                                                                                                  key={todo.id}
                                                                                                                                                                                                                                                                                className={`todo-item ${todo.completed ? 'completed' : ''}`}
                                                                                                                                                                                                                                                                                            >
                                                                                                                                                                                                                                                                                                          <input
                                                                                                                                                                                                                                                                                                                          type="checkbox"
                                                                                                                                                                                                                                                                                                                                          checked={todo.completed}
                                                                                                                                                                                                                                                                                                                                                          onChange={() => toggleComplete(todo.id)}
                                                                                                                                                                                                                                                                                                                                                                        />
                                                                                                                                                                                                                                                                                                                                                                                      <span>{todo.text}</span>
                                                                                                                                                                                                                                                                                                                                                                                                  </li>
                                                                                                                                                                                                                                                                                                                                                                                                            ))}
                                                                                                                                                                                                                                                                                                                                                                                                                    </ul>
                                                                                                                                                                                                                                                                                                                                                                                                                          )}